name: Auto merge dependabot pull requests

# TOKEN SCOPE
# The GitHub token is a [Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with the following scopes:
# `repo` for private repositories
# `public_repo` for public repositories
#
# The token MUST be created from a user with push permission to the repository.

on:
  workflow_call:
    secrets:
      personal_access_token:
        required: true

jobs:
  auto-merge-dependabot:
    name: Approve and merge pending pull requests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: |
          gh pr list --author "dependabot[bot]" --json number,statusCheckRollup,mergeable --jq '.[] | select(.statusCheckRollup | length > 0 and all(.[]; .conclusion == "SUCCESS")) | select(.mergeable == "MERGEABLE") | .number' | while read i; do
            echo "Processing PR #$i"

            # Approve the PR
            if gh pr review $i --approve; then
              echo "✓ Approved PR #$i"
            else
              echo "⚠ Failed to approve PR #$i, continuing..."
            fi

            # Try to merge the PR, continue on failure
            if gh pr merge $i --squash; then
              echo "✓ Merged PR #$i"
            else
              echo "⚠ Failed to merge PR #$i, will retry later"
            fi

            echo "---"
          done
        env:
          GH_TOKEN: ${{ secrets.personal_access_token }}
